# Copyright (C) 2017 NVIDIA Corporation.  All rights reserved.
# Licensed under the CC BY-NC-SA 4.0 license (https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode).

# logger options
image_save_iter: 10000        # How often do you want to save output images during training
image_display_iter: 100       # How often do you want to display output images during training
display_size: 4               # How many images do you want to display each time
snapshot_save_iter: 10000     # How often do you want to save trained models
log_iter: 1                   # How often do you want to log the training stats

# optimization options
max_iter: 200                # maximum number of training iterations
batch_size: 1                 # batch size
weight_decay: 0.0005          # weight decay
beta1: 0.5                    # Adam parameter
beta2: 0.999                  # Adam parameter
init: kaiming                 # initialization [gaussian/kaiming/xavier/orthogonal]
lr: 0.00002                    # initial learning rate
lr_policy: step               # learning rate scheduler
step_size: 100                # how often to decay learning rate
gamma: 0.9                    # how much to decay learning rate
gan_w: 0.5                     # weight of adversarial loss
recon_x_w: 2                 # weight of image reconstruction loss
recon_h_w: 0                  # weight of hidden reconstruction loss
recon_kl_w: 0.0001              # weight of KL loss for reconstruction
recon_x_cyc_w: 10             # weight of cycle consistency loss
recon_kl_cyc_w: 0.0001          # weight of KL loss for cycle consistency
vgg_w: 0.1                      # weight of domain-invariant perceptual loss

# model options
gen:
  dim: 64                     # number of filters in the bottommost layer
  activ: lrelu                 # activation function [relu/lrelu/prelu/selu/tanh]
  n_downsample: 3             # number of downsampling layers in content encoder
  n_res: 4                   # number of residual blocks in content encoder/decoder
  pad_type: zero           # padding type [zero/reflect]
dis:
  dim: 32                     # number of filters in the bottommost layer
  norm: in                  # normalization layer [none/bn/in/ln]
  activ: lrelu                # activation function [relu/lrelu/prelu/selu/tanh]
  n_layer: 3                  # number of layers in D
  gan_type: lsgan             # GAN loss [lsgan/nsgan]
  num_scales: 3              # number of scales
  pad_type: zero           # padding type [zero/reflect]

# data options
input_dim_a: 1                              # number of image channels for NII data (typically grayscale)
input_dim_b: 1                              # number of image channels for NII data (typically grayscale)
num_workers: 8                             # number of data loading threads
new_size: [128 , 128, 128]                    # new size for 3D NII data (resize each dimension)
crop_image_height: 128                      # crop image height for 3D data
crop_image_width: 128                       # crop image width for 3D data
crop_image_depth: 128                        # crop image depth for 3D data

# Add a flag for handling NII data
## data_type: nii                              # specify the type of data being loaded ('nii')

data_root: ./datasets/anata2fatfrac/        # dataset folder location
